name: cosanostr
description: PWA Nostr Client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^4.0.4
  nostr_tools: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
