// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb63A_4fMzA8cNQ9ovnuxJnRHRNXDNsDw',
    appId: '1:505671824716:web:23e353abcf54ed21bc0be9',
    messagingSenderId: '505671824716',
    projectId: 'cosanostr',
    authDomain: 'cosanostr.firebaseapp.com',
    storageBucket: 'cosanostr.appspot.com',
    measurementId: 'G-9E8LF5TRXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSviI-ef-2QCszPGjjh32lFcQAXnbVeZw',
    appId: '1:505671824716:android:e363b64efb1198b1bc0be9',
    messagingSenderId: '505671824716',
    projectId: 'cosanostr',
    storageBucket: 'cosanostr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdyt8w6Z7Nn_MnTOAws6q4Yn7fEyuqAZE',
    appId: '1:505671824716:ios:05817b7dc0e71892bc0be9',
    messagingSenderId: '505671824716',
    projectId: 'cosanostr',
    storageBucket: 'cosanostr.appspot.com',
    iosClientId:
        '505671824716-ojp1skq17kqbls9e716nak2akvvp39om.apps.googleusercontent.com',
    iosBundleId: 'dev.plotsklapps.cosanostr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdyt8w6Z7Nn_MnTOAws6q4Yn7fEyuqAZE',
    appId: '1:505671824716:ios:0f980decfcb5671dbc0be9',
    messagingSenderId: '505671824716',
    projectId: 'cosanostr',
    storageBucket: 'cosanostr.appspot.com',
    iosClientId:
        '505671824716-290m9kscbdsju8fabf8pvaqc3c7rm8tg.apps.googleusercontent.com',
    iosBundleId: 'dev.plotsklapps.cosanostr.RunnerTests',
  );
}
